### PR TITLE
Fix typos in README.md

### PR DESCRIPTION
**Pull request by newyork-anthonyng**

### CODE REVIEW

**Comment by yaycmyk** [comment]
@newyork-anthonyng thanks for this, can you actually make the changes in the respective `index.js` files instead? Those READMEs are autogenerated from them.

**Comment by yaycmyk** [comment]
@newyork-anthonyng Could you rebase, and it looks like there was a linting error that caused the build to fail. You can call `npm run release` and commit the result of that if you'd like to see your changes reflected immediately in the files :)

**Comment by newyork-anthonyng** [comment]
@yaycmyk Thanks for walking me through this.

I did the `rebase` and ran `npm run release` and committed the results of it.

There were a number of files that changed from it, so I'm not sure if I did it correctly. Let me know if there's anything that needs to be updated.

**Comment by yaycmyk** [comment]
Looks good, thanks for contributing!

**Pull request merged**
